name = "Stada"
description = "Clean minimalistic theme with nice adaptive"
homepage = "https://github.com/denisotree/hugo-theme-stada"
license = "MIT"
licenselink = "https://github.com/denisotree/hugo-theme-stada/blob/master/LICENSE.md"
tags = ["responsive", "blog", "minimalistic", "clean", "pure", "strada"]
features = ["responsive", "grid", "scss", "darkmode"]
min_version = "0.1.0"

[author]
  name = "Denis Vdovin"
  homepage = "https://dblog.me/"